#!/usr/bin/env python3
"""Separate deterministic export of resources and conceptual diagrams."""
import argparse
import json
from datetime import datetime, timezone
from validate import ROOT
from validate_extra import validate_all

def latest_review_date(resources, diagrams):
    timestamps = [r['freshness']['reviewed_at'] for r in resources] + [d['reviewed_at'] for d in diagrams]
    return max(datetime.fromisoformat(value.replace('Z', '+00:00')).astimezone(timezone.utc) for value in timestamps).date().isoformat()

def build_export():
    resources,diagrams,taxonomy=validate_all()
    return {'schema_version':'1.0.0','dataset':'security-research-library-resources','as_of':latest_review_date(resources, diagrams),'repository_url':'https://github.com/gkdataio/security-research-library','scope':'Official defensive education and conceptual models; separate from qualifying award reports','counts':{'resources':len(resources),'diagrams':len(diagrams)},'taxonomy':taxonomy,'skillset_definitions':json.loads((ROOT/'data/taxonomy.json').read_text())['skillsets'],'resources':resources,'diagrams':diagrams,'asset_note':'Diagram asset paths are relative to the repository. SVGs are generated by Graphviz from the same canonical node/edge graph as the Mermaid sources; a Mermaid engine was not executed.'}

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args()
    text=json.dumps(build_export(),ensure_ascii=False,indent=2)+'\n';target=ROOT/'exports/resources.json'
    if a.check:
        if not target.is_file() or target.read_text()!=text:p.exit(1,'Resources export missing or stale.\n')
        print('Resources export is current and deterministic.')
    else:target.write_text(text);print(target)
